DB_USER = "root"
DB_PASSWORD = "12345678"
DB_HOST = "localhost"
DB_NAME = "LucidFinancials"
DATABASE_URL = f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}"

MAX_POST_SIZE = 1024 * 1024
POSTS_RESPONSE_CACHE_SECONDS = 300
API_TOKEN_EXPIRE_MINUTES = 60

SECRET_KEY = "your_secret_key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30